name: Generate Keystore

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Keystore
        run: |
          keytool -genkeypair -v -keystore unilens-release.jks -alias unilens \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -storepass "UniLensSecret2026" -keypass "UniLensSecret2026" \
            -dname "CN=UniLens, OU=Mobile, O=UniLens, L=Unknown, S=Unknown, C=US"
      
      - name: Upload Keystore Artifact
        uses: actions/upload-artifact@v4
        with:
          name: permanent-keystore
          path: unilens-release.jks
